Stufff

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -50,6 +50,14 @@ jobs:
         }
       shell: pwsh
 
+    # Check if VERSION is set
+    - name: Check if VERSION is set
+      run: |
+        if ("${{ env.VERSION }}" == "") {
+          echo "Error: VERSION is not set. Cannot create a GitHub release without a tag name."
+          exit 1
+        }
+
     - name: Delete existing tag
       run: |
         git tag -d ${{ env.VERSION }} || true
@@ -61,6 +69,7 @@ jobs:
         git push origin ${{ env.VERSION }}
 
     - name: Create GitHub Release
+      if: env.VERSION != ''
       uses: actions/create-release@v1
       with:
         tag_name: ${{ env.VERSION }}
